# Generated by Django 2.2.11 on 2020-03-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teampluginmodel',
            old_name='team',
            new_name='members',
        ),
    ]
